services:
  - type: web
    name: prezenty
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DB_HOST
        value: 153.92.7.101
      - key: DB_USER
        value: u662139794_prezenty
      - key: DB_PASSWORD
        sync: false  # You'll need to set this manually in Render dashboard
      - key: DB_NAME
        value: u662139794_prezenty
      - key: DB_PORT
        value: 3306
