services:
  - type: web
    name: prezenty
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: <your_postgres_connection_string>
    # Add a persistent disk for uploads
    disks:
      - name: uploads
        mountPath: /app/public/uploads
        sizeGB: 1 # Adjust as needed
